- hosts: localhost
  remote_user: vagrant
  serial: 1
  roles:
    - common
    - oracle-java-develop
    - docker
    - docker-compose
#    - docker-machine
    - maven
    - jenkins2-docker
    - jenkins-node
    - sonarqube
